// Generates public/robots.txt and public/sitemap.xml at build time.
//
// Runs automatically via `npm run build` (see package.json). The production
// domain comes from VITE_SITE_URL — set it in the deploy environment and the
// canonical tags, robots and sitemap all follow from that single value.
//
// Project detail routes are read out of src/assets/assets.js so the sitemap
// cannot drift from the real listing data.
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const PLACEHOLDER_ORIGIN = 'https://www.murrayinvestments.example'
const ORIGIN = (process.env.VITE_SITE_URL || PLACEHOLDER_ORIGIN).replace(/\/+$/, '')

// Extract the `id:` of every entry in projectsData (not testimonials etc.)
function projectIds() {
    const source = readFileSync(path.join(ROOT, 'src/assets/assets.js'), 'utf8')
    const block = source.slice(source.indexOf('export const projectsData'))
    const ids = [...block.matchAll(/^\s{4,6}id:\s*(\d+),/gm)].map((m) => Number(m[1]))
    if (!ids.length) {
        throw new Error('generate-seo: found no project ids in assets.js — check the projectsData shape')
    }
    return ids
}

const ids = projectIds()
const today = new Date().toISOString().slice(0, 10)

// changefreq/priority are hints only; kept conservative and honest.
const routes = [
    { loc: '/', changefreq: 'monthly', priority: '1.0' },
    // /properties is the canonical browsing route; the legacy /projects paths
    // redirect to it and are deliberately excluded from the sitemap.
    { loc: '/properties', changefreq: 'monthly', priority: '0.8' },
    { loc: '/about', changefreq: 'yearly', priority: '0.6' },
    ...ids.map((id) => ({ loc: `/properties/${id}`, changefreq: 'yearly', priority: '0.7' })),
]

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-seo.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
        .map(
            (r) => `  <url>
    <loc>${ORIGIN}${r.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`
        )
        .join('\n')}
</urlset>
`

// Everything public is crawlable. Only build/runtime resources that carry no
// standalone search value are excluded.
const robots = `# Generated by scripts/generate-seo.mjs — do not edit by hand.
User-agent: *
Allow: /
Disallow: /assets/
Disallow: /fonts/

Sitemap: ${ORIGIN}/sitemap.xml
`

writeFileSync(path.join(ROOT, 'public/sitemap.xml'), sitemap)
writeFileSync(path.join(ROOT, 'public/robots.txt'), robots)

console.log(`generate-seo: origin ${ORIGIN}${ORIGIN === PLACEHOLDER_ORIGIN ? '  ** PLACEHOLDER — set VITE_SITE_URL before launch **' : ''}`)
console.log(`generate-seo: ${routes.length} urls (${ids.length} project pages)`)
